stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - .pip_cache/
    - venv/
    - .docker_cache/

install:
  stage: install
  image: python:3.8-slim
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
  tags:
    - docker

test:
  stage: test
  image: python:3.8-slim
  script:
    - source venv/bin/activate
    - pytest --cov=your_module tests/test_model.py

build:
  stage: build
  image: docker:latest
  script:
    - docker info
    - docker build -t Deer_Population_Prediction --file devcontainer/Dockerfile .
  only:
    - main
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

deploy:
  stage: deploy
  image: python:3.8-slim
  script:
    - echo "Deploying to production..."
    - docker run --rm Deer_Population_Prediction
  only:
    - main

deploy_staging:
  stage: deploy
  image: python:3.8-slim
  script:
    - echo "Deploying to staging..."
    - docker run --rm Deer_Population_Prediction
  only:
    - staging
